### DISCUSSION TITLE
How to use GitHub Actions to build and/or deploy an Observable Framework project

### DISCUSSION THREAD

**Discussion by ModelEarth** [observablehq/framework#1030] [Q&A] [answered]
[The Getting Started Page](https://observablehq.com/framework/getting-started) provides a deploy.yml sample for a Yarn deployment of documentation website.
(Running the more complex deploy.yml on the hello-framework fails with: Command"doc.build" not found.)

Below Mike has posted samples for both yarn and npm deploy.yml files for the hello-framework starter.

Mike's post on GitHub Pages deployments using deploy.yml avoids adding .nojekyll file. Pretty awesome! (We're fans of Cloudflare hosting too - looking forward to taking model.earth to Cloudflare Page as we integrate Observable with [Chatbot UI](https://github.com/mckaywrigley/chatbot-ui).)

If you don't use the Github Action setups using deploy.yml described in the posts below, here are several ways to create a site from the static files in your "dist" folder without adding deploy.yml:

1a.) Remove dist/ from the .gitignore file.
1b.) Point GitHub pages at your repo.

The resulting URL includes "/dist"
https://[account].github.io/hello-framework/dist

For the sample above, you'll see a 404 error if you don't include "/dist" in the URL.

2.) You can place the dist files in the root of a repo or in a "docs" folder ("docs" is the only subfolder GitHub Pages lists. Is there a way to tell GitHub Pages to point into the dist folder?).

IMPORTANT: Add an empty .nojekyll file to the root directory (if you're not using deploy.yml), otherwise your Github Pages will be broken. Jekyll is the default page renderer for GH pages, and it ignores directories that begin with an underscore. Thanks [Philippe Rivière](https://github.com/Fil)!

3.) In Github, under Settings > Pages > Build and Deploy, choose "Deploy from branch: Source" and activate the static.yml file.

Notes:

If selecting GitHub Pages  and "/docs" prevents the error: "docs:build" not found error in deploy.yml with the hello-framework site, BUT the site still has broken formatting and no navigation -- try adding an empty .nojekyll file to your docs folder. (You'll probably see raw code because the docs folder in the hello-observable repo contains src files.)

When you choose "Deploy from branch", the source choice will disappear.

Here's the more complex deploy.yml used for the documentation site from the bottom of the Getting Started page:
https://github.com/observablehq/framework/blob/main/.github/workflows/deploy.yml

Check out the deploy.yml examples from Mike below for running hello-framework on GitHub Pages and Cloudflare.

**Comment by mbostock** [comment, marked as answer]
I moved this to a discussion because it sounds like you’re asking how to use GitHub Actions to build and/or deploy an Observable Framework project. The [deploy.yml](https://github.com/observablehq/framework/blob/main/.github/workflows/deploy.yml) we use is provided as reference, but it isn’t intended to work out of the box for all projects — there are quite a few ways in which are deploy.yml is tailored uniquely to the needs of building the Observable Framework documentation (which is itself an Observable Framework project).

Here’s a smaller example of a GitHub Actions deploy workflow, setup to deploy on either (1) a daily schedule at 10:15 AM UTC, (2) on pushes to the main branch, and (3) manually.

```yaml
name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  schedule:
    - cron: "15 10 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Deploy to Observable
        run: yarn deploy -m "$(git log -1 --pretty=%s)"
        env:
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_API_TOKEN }}
```

The action above assumes Yarn. It also requires you to set the `OBSERVABLE_API_TOKEN` [GitHub environment secret](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions). You can create an Observable API key by going here:

```
https://observablehq.com/team/@{login}/settings/api-keys?tab=apiKeys
```

where `{login}` should be replaced with your Observable workspace name (for me, that’s `mbostock` or `observablehq`).

The equivalent action with npm would look something like this:

```yaml
name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  schedule:
    - cron: "15 10 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy to Observable
        run: npm run deploy -- -m "$(git log -1 --pretty=%s)"
        env:
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_API_TOKEN }}
```

**Comment by ModelEarth** [comment]
Thanks! Looking forward to implementing!

When displaying the content of "dist" as static files in GitHub Pages, if you encounter formatting issues, add an empty .nojekyll file.

These first two work only with .nojekyll file added:

1.) Dist files in the [root of repo](https://github.com/ModelEarth/hello-framework-root)
https://model.earth/hello-framework-root/

2.) Dist files in the docs folder with Github Pages [pointed into docs](https://github.com/ModelEarth/hello-framework-docs)
https://model.earth/hello-framework-docs/
(Required a deploy refresh after adding the empty .nojekyll file.)

3.) Works here (with /dist removed in .gitignore):
https://model.earth/hello-framework/dist/
The dist files above display correctly in a subfolder because files with underscores are only blocked by Jekyll at the site root. So  a .nojekyll file is not needed with this third option.

Related quesiton: (Mike answers below) Does the [Observable Framework main site](https://github.com/observablehq/framework/tree/main) repo have GitHub Pages pointed at its "docs" folder? Or is "Deploy from Branch" selected instead? (Both under Settings > Pages)

**Reply by Fil** [reply]
You may have to add an empty .nojekyll file to the root directory, because jekyll is the default page renderer for GH pages, and it ignores directories that begin with an underscore.
https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

**Reply by ModelEarth** [reply]
Brilliant! Adding the .nojekyll file worked for the "dist" pages copied into the root of a repo. AND it worked for the GitHub Pages pointed into "docs" too! (I had to run a deploy to refresh that one.) I've updated the posts above. Thanks!

**Reply by mbostock** [reply]
We don’t use GitHub Pages for our documentation; we use Cloudflare Pages. If you want to deploy to GitHub Pages, you need something like this:

```yaml
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

You’ll also need some permissions:

```yaml
permissions:
  contents: read
  pages: write
  id-token: write
```

See:

* https://github.com/actions/configure-pages
* https://github.com/actions/upload-pages-artifact
* https://github.com/actions/deploy-pages

If you use this approach you shouldn’t need the `.nojekyll` file or to configure anything in the GitHub UI (other than enabling pages, maybe?). The process is similar to [deploying a VitePress site](https://vitepress.dev/guide/deploy#github-pages).
