### DISCUSSION TITLE
Including a PNG background image in custom CSS stylesheet

### DISCUSSION THREAD

**Discussion by michalc** [observablehq/framework#1501] [Q&A] [answered]
I'm including some custom styles using the `style` option at https://observablehq.com/framework/config#style

For the most part they work great, but I would like to include a PNG background image. If I try to include this in my stylesheet:

```css
.my_class {
  background-image: url("my_image.png");
}
```
Then I get the error:
```
[ERROR] No loader is configured for ".png" files: src/my_image.png
```
How can I avoid the error / include PNG background images in my custom CSS?
