### DISCUSSION TITLE
Deploy not configured error in github action

### DISCUSSION THREAD

**Discussion by WillHWThompson** [observablehq/framework#1553] [Q&A]
I am trying to deploy my dashboard via a github action following the documentation [here](https://observablehq.com/framework/deploying). 

Here is the 
```yml
name: Deploy

on:
  push:
    branches: [main]
  schedule: 
    - cron: "15 10 * * *"
  workflow_dispatch: {}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'

      - name: Cache Python packages
        id: cache-python-packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Cache databases directory
        id: cache-databases
        uses: actions/cache@v3
        with:
          path: databases
          key: ${{ runner.os }}-databases-${{ hashFiles('dashboard_src/create_database.py') }}
          restore-keys: |
            ${{ runner.os }}-databases-

      - name: Check Cache Hit Status
        run: |
          echo "Cache hit: ${{ steps.cache-databases.outputs.cache-hit }}"

      - name: Pull newest data from Airtable
        if: steps.cache-databases.outputs.cache-hit != 'true'
        run: |
          mkdir -p databases
          python dashboard_src/create_database.py
          
      - run: npm ci
      - run: npm run build 

      - name: Deploy to Observable Cloud
        run: |
          npm run deploy --deploy-config=docs/.observablehq/deploy.json --debug --message "$(git log -1 --pretty=%s)"
        env:
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}
```

And my deploy.json looks like this:
```
{
  "projected": "<project_id>",
   "projectSlug": "<project slug>",
    "workspaceLogin": "<login>"
  }
  ```
  
  I have verified that the `OBSERVABLE_TOKEN` is indeed configured in the repo. 
  
  I can deploy locally perfectly fine, but when I run the GitHub action I get the following error: 
  
  ```
Run npm run deploy --deploy-config=docs/.observablehq/deploy.json --debug --message "$(git log -1 --pretty=%s)"

> deploy
> observable deploy

┌   observable deploy 
│
└  Error: Deploy not configured.

Error: Process completed with exit code 1.
```
Where else can I look for a problem? I've verified the Observable token and explicitly set the path to the deploy.json file. What else could be causing the error?
