### DISCUSSION TITLE
Build Error and Parameterized Route Pages Missing

### DISCUSSION THREAD

**Discussion by oscaro00** [observablehq/framework#1792] [Q&A] [answered]
Hello,

I am trying to add some parameterized routes to my Framework dashboard. I added dynamic paths to the config file

```js
dynamicPaths: [
  "/presets/evens",
  "/presets/odds"
]
```

and added `src/presets/[preset].md`. Within `src/presets/[preset].md`, I added the code

```
The current preset is ${observable.params.preset}.
```

After running `npm run dev`, my dashboard loads, but the preset pages are not there. Looking at this [discussion](https://github.com/observablehq/framework/discussions/1771), I saw mbostock build his dashboard. However, running `npm run build` (for the first time since creating this project) gave the following error:

```
Warning: the output root dist is not within the current working directory and will not be cleared.
load /index in 485ms
load /inventory-summary in 46ms
load /pos-summary in 47ms
load /presets/evens in 70ms
load /presets/odds in 59ms
built 5 pages in src
bundle /_observablehq/client.js → src/.observablehq/cache/_observablehq/client.js
bundle /_observablehq/runtime.js → src/.observablehq/cache/_observablehq/runtime.js
bundle /_observablehq/stdlib.js → src/.observablehq/cache/_observablehq/stdlib.js
bundle /_observablehq/stdlib/duckdb.js → src/.observablehq/cache/_observablehq/stdlib/duckdb.js
bundle /_observablehq/stdlib/inputs.js → src/.observablehq/cache/_observablehq/stdlib/inputs.js
build src/style.css → dist/_import/style.9ff5b03d.css

Unexpected error: file conflict: /_import/style.9ff5b03d.css
```

I have a `style.css` file that doesn't do anything special. Here is a snippet of the file

```css
@import url("observablehq:default.css");
@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css");
/* @import url("./abstract-light.css"); */

:root {
    --theme-foreground: #1b1e23;
    --theme-foreground-focus: #3b5fc0;
    --theme-background-a: #ffffff;
}

:root {
    --theme-background-b: color-mix(in srgb, var(--theme-foreground) 4%, var(--theme-background-a));
    --theme-background: var(--theme-background-a);
    --theme-background-alt: var(--theme-background-b);
    --theme-foreground-alt: color-mix(in srgb, var(--theme-foreground) 90%, var(--theme-background-a));
    --theme-foreground-muted: color-mix(in srgb, var(--theme-foreground) 60%, var(--theme-background-a));
    --theme-foreground-faint: color-mix(in srgb, var(--theme-foreground) 50%, var(--theme-background-a));
    --theme-foreground-fainter: color-mix(in srgb, var(--theme-foreground) 30%, var(--theme-background-a));
    --theme-foreground-faintest: color-mix(in srgb, var(--theme-foreground) 14%, var(--theme-background-a));
    color-scheme: light;
}

/* css classes continue */
```

I am not really sure what is causing the build to fail. Additionally, is running `npm run build` the only way to see the parameterized routes?
