### DISCUSSION TITLE
Avoid space around css pseudo elements

### DISCUSSION THREAD

**Discussion by Martien** [observablehq/framework#1834] [Q&A] [answered]
I assume this is a very specific edge case. I #daretoask anyway.

I need a `<div class="context">` to start with …, seamlessly followed by its text, e.g. like so:

    …the distribution of towns required to make a balanced region

So in `style.css` I have:

```css
.context::before,
{
    content: "…";
    display: inline;
    margin: 0;
    margin-block: 0;
    margin-inline: 0;
}
div.context > p {
    display: inline;
    margin: 0;
    margin-block: 0;
    margin-inline: 0;
}
```

However, **this renders space between … and text** because Framework seems to generate:

```html
<div class="context">
    <p>aloha</p>
</div>
```

I can get rid of the space by removing any white space between the `<div>` and the `<p>`, like so:

```html
<div class="context"><p>text</p></div>
```

But as the html is generated, there seems to be nothing that I can do (apart from generating it myself, e.g. using a Page Loader).

How to get rid of that space?

P.S. all the margin settings may be superfluous.
