### DISCUSSION TITLE
Build command failing

### DISCUSSION THREAD

**Discussion by justuswitmer** [observablehq/framework#1895] [Q&A] [answered]
Hello, I am working on deploying an Observable App via GitHub Actions. I am using the example workflow given in the [Observable docs](https://observablehq.com/framework/deploying#git-hub-actions). I can run everything locally. I can even run the `npm run build` command just fine, but when I run it via GitHub Actions it errors out. The issue seems to be with the data loader. I have a loader called `get-locations.json.js`, but the process is looking for `get-locations.json` and errors out when it can't find it. I assumed that during the build process `get-locations.json` was going to be generated, but it doesn't seem to be the case. Has anybody else run into this issue?

Here is the error from the GitHub Actions workflow:
```
TypeError: Invalid URL
    at new URL (node:internal/url:804:36)
    at parseUrl (file:///home/runner/work/sonnys-notebooks/sonnys-notebooks/node_modules/postgres/src/index.js:543:18)
    at parseOptions (file:///home/runner/work/sonnys-notebooks/sonnys-notebooks/node_modules/postgres/src/index.js:435:30)
    at Postgres (file:///home/runner/work/sonnys-notebooks/sonnys-notebooks/node_modules/postgres/src/index.js:50:19)
    at alfred (file:///home/runner/work/sonnys-notebooks/sonnys-notebooks/src/data/alfred.js:14:15)
    at file:///home/runner/work/sonnys-notebooks/sonnys-notebooks/src/data/get-locations.json.js:3:20
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12) ***
  code: 'ERR_INVALID_URL',
  input: '***undefined:undefined/undefined'
***

Node.js v21.7.3
copy src/data/get-locations.json → load /data/get-locations.json → [missing] error in 57ms: loader exited with code 1
``` 

And here is my GitHub Actions workflow:
```
name: Deploy

on:
  push: {branches: [main]}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
```
