### ISSUE TITLE
Better support for DuckDB extensions

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1070]
It would be great to be able to install/load [DuckDB extensions](https://duckdb.org/docs/extensions/overview.html) as simply as:

```yaml
---
sql:
  install: [httpfs, spatial]
  tables:
    taxis: nyc-taxis.parquet
---
```

https://github.com/observablehq/framework/issues/1007

(This means we'll need to extend the shape of the sql front matter option, see #1054)
