### ISSUE TITLE
Support for sql remote URLs

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1071]
```yaml
---
sql:
  gaia: https://uwdata.github.io/mosaic-datasets/data/gaia-5m.parquet
---
```

An alternative to consider / a complement would be to allow `FileAttachment("https://uwdata.github.io/mosaic-datasets/data/gaia-5m.parquet"[, options])`; the options could indicate the extension/mimeType.
