### ISSUE TITLE
Support remote and local assets in custom CSS

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#1573]
See #1372; related #786.

**Comment by Arijitdesignsit** [comment]
I have been trying to go around this issue for a long time now. I am able to solve it via D3js today.
So, I just simply took the served absolute URL of the image by
```
const imgURL = await FileAttachment("./exampleImage.jpg").href;
```

Then by doing the following I am able to put a background image in a div with id divId:
```
d3.select("#divId").style("background-image", "url("+imgURL+")");
```

**Comment by Fil** [comment]
It's possible to work around the issue and host these fonts within your data app, but it requires a little bit of juggling. Here's my current approach:
https://observablehq.observablehq.cloud/framework-example-font-face/?secret=w7WHOz2YV5uW-V0Bml5Cmwvc7hEsVOAfm2RRwuh-vu4

(I'm sharing in case it can unblock someone, but it would be better to fix the issue.)

**Comment by drom** [comment]
Thank you for the great framework!

I am trying to load local font in my custom `style.css` 

```css
@font-face {
  font-family: 'Iosevka Drom Web';
  font-display: swap;
  font-weight: 400;
  font-stretch: normal;
  font-style: normal;
  src: url("./IosevkaDrom-Regular.woff2") format('woff2');
}
```

And getting this error:

![Image](https://github.com/user-attachments/assets/c2c013ed-9ee7-4a10-8990-3225bc271e48)

Is there other way I should try?

Self hosting custom fonts is a critical requirement for my projects. It would be nice if there was a way to implement it.
