### ISSUE TITLE
uncaught front-matter errors

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#215]
If the front-matter is invalid, the preview server can crash.

example:

```yaml
---
toc:
  show: false
title: "Welcome"
dd==::1
---
```

we should probably try catch this:
https://github.com/observablehq/cli/blob/af451f56694c6fd207b0ef50b56c206bcf98aa52/src/markdown.ts#L381
